# Generated by Django 3.2.25 on 2024-08-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20240802_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gathering',
            name='date',
        ),
        migrations.RemoveField(
            model_name='gathering',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='gathering',
            name='title',
        ),
        migrations.AddField(
            model_name='gathering',
            name='activity_scope',
            field=models.CharField(choices=[('online', '온라인'), ('offline', '오프라인')], default='활동 범위', max_length=10),
        ),
        migrations.AddField(
            model_name='gathering',
            name='chat_link',
            field=models.CharField(default='단톡방 링크', max_length=255),
        ),
        migrations.AddField(
            model_name='gathering',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gathering',
            name='location',
            field=models.CharField(default='시 / 군 / 구', max_length=100),
        ),
        migrations.AddField(
            model_name='gathering',
            name='name',
            field=models.CharField(default='모임의 이름', max_length=100),
        ),
        migrations.AddField(
            model_name='gathering',
            name='status',
            field=models.CharField(choices=[('recruiting', '모집중'), ('closed', '마감됨')], default='모집 상태', max_length=10),
        ),
        migrations.AddField(
            model_name='gathering',
            name='subject',
            field=models.CharField(default='모임의 주제', max_length=100),
        ),
    ]
