# Generated by Django 3.2.25 on 2024-08-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240802_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardsComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'boards_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardsGathering',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('activity_scope', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('chat_link', models.CharField(max_length=255)),
                ('likes', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'boards_gathering',
                'managed': False,
            },
        ),
    ]
