# Generated by Django 3.2.25 on 2024-07-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('introduction', models.TextField(max_length=300)),
                ('members_count', models.IntegerField(default=0)),
                ('chat_link', models.URLField(blank=True)),
                ('activity_scope', models.CharField(blank=True, max_length=100)),
                ('recruitment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(error_messages={'unique': '이미 사용중인 별명입니다'}, max_length=20, unique=True)),
                ('introduction', models.TextField(blank=True, max_length=150)),
                ('password', models.CharField(max_length=20)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('tier', models.CharField(choices=[('tier1', 'Bronze'), ('tier2', 'Silver'), ('tier3', 'Gold'), ('tier4', 'Diamond')], max_length=10)),
                ('consecutive_attendance_days', models.IntegerField(default=0)),
                ('joined_groups', models.ManyToManyField(blank=True, related_name='members', to='accounts.Group')),
            ],
        ),
    ]
