# Generated by Django 3.2.25 on 2024-08-04 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=100, null=True)),
                ('management', models.CharField(blank=True, max_length=100, null=True)),
                ('acceptible', models.CharField(max_length=100)),
                ('unacceptible', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Bin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapoDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Mapo_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='pictures/')),
                ('bin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maps.bin')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('bin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maps.bin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
