# Generated by Django 3.2.25 on 2024-08-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'managed': False},
        ),
    ]
