# Generated by Django 3.2.25 on 2024-08-08 12:55


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20240806_0117'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pictures',
            table='Pictures',
        ),
    ]
