# Generated by Django 3.2.25 on 2024-07-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionBin',
            fields=[
                ('bin_id_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_location', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='bins/<int:pk>')),
                ('description', models.TextField()),
                ('acceptable_items', models.TextField()),
                ('unacceptable_items', models.TextField()),
            ],
        ),
    ]
