# Generated by Django 3.2.25 on 2024-07-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.IntegerField()),
                ('content', models.CharField(max_length=300)),
                ('created_dt', models.DateTimeField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('board_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('scrap_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Scrap',
                'managed': False,
            },
        ),
    ]
