# Generated by Django 3.2.25 on 2024-07-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=300)),
                ('likes', models.IntegerField()),
                ('created_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'Comment',
                'managed': False,
            },
        ),
    ]
