# Generated by Django 3.2.25 on 2024-08-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20240807_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='HkbsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.URLField()),
                ('img_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Article',
            new_name='BbcArticle',
        ),
    ]
