# Generated by Django 3.2.25 on 2024-08-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20240809_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hkbsarticle',
            old_name='img_url',
            new_name='image_url',
        ),
    ]
